app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

projects:
    resource: "@AppBundle/Controller/ProjectController.php"
    type :  annotation

delete:
    path: /projects/delete/{id}
    defaults:
        _controller: AppBundle:Projects:delete


login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout